version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kuhi-frontend:latest
    ports:
      - "8080:80"         # acesso em http://localhost:8080
    restart: unless-stopped
    environment:
      - NODE_ENV=production
